# Generated by Django 3.1.3 on 2020-11-24 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('product_type', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.productcategory')),
            ],
        ),
    ]
