# Generated by Django 3.1.3 on 2020-12-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201203_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
